.pragma library

function list() {
    return [
        ["😀","grinning face","content joie sourire"],["😃","grinning face big eyes","content joie sourire"],
        ["😄","grinning face smiling eyes","content joie sourire rire"],["😁","beaming face","content joie sourire"],
        ["😆","grinning squinting face","rire content"],["😅","grinning sweat","rire gene"],
        ["🤣","rolling on floor laughing","rire mdr"],["😂","face with tears of joy","rire mdr larmes"],
        ["🙂","slightly smiling face","sourire"],["🙃","upside down face","ironie"],
        ["😉","winking face","clin oeil"],["😊","smiling face blush","content gentil"],
        ["😇","smiling face halo","ange innocent"],["🥰","smiling face hearts","amour coeur"],
        ["😍","heart eyes","amour coeur adore"],["🤩","star struck","impressionne wahou"],
        ["😘","face blowing kiss","bisou amour"],["😗","kissing face","bisou"],
        ["😚","kissing closed eyes","bisou"],["😙","kissing smiling eyes","bisou"],
        ["😋","face savoring food","miam delicieux"],["😛","face with tongue","tire langue"],
        ["😜","winking tongue","tire langue clin oeil"],["🤪","zany face","fou dingue"],
        ["😝","squinting tongue","tire langue"],["🤑","money mouth","argent"],
        ["🤗","hugging face","calin"],["🤭","hand over mouth","chut oups"],
        ["🤫","shushing face","chut silence"],["🤔","thinking face","reflexion penser"],
        ["🤐","zipper mouth","silence secret"],["🤨","raised eyebrow","doute suspicion"],
        ["😐","neutral face","neutre"],["😑","expressionless","blase"],
        ["😶","no mouth","silence"],["😏","smirking face","malicieux"],
        ["😒","unamused face","blase agace"],["🙄","rolling eyes","lassitude"],
        ["😬","grimacing face","gene grimace"],["🤥","lying face","mensonge"],
        ["😌","relieved face","soulage"],["😔","pensive face","triste reflexion"],
        ["😪","sleepy face","fatigue dodo"],["🤤","drooling face","envie miam"],
        ["😴","sleeping face","dodo fatigue"],["😷","face with medical mask","malade masque"],
        ["🤒","face with thermometer","malade fievre"],["🤕","face with bandage","blesse"],
        ["🤢","nauseated face","degoute malade"],["🤮","vomiting face","malade degoute"],
        ["🥵","hot face","chaud"],["🥶","cold face","froid"],
        ["🥴","woozy face","etourdi ivre"],["😵","dizzy face","etourdi ko"],
        ["🤯","exploding head","choque wahou"],["🤠","cowboy face","cowboy"],
        ["🥳","partying face","fete anniversaire"],["😎","sunglasses face","cool style"],
        ["🤓","nerd face","intello"],["🧐","face monocle","reflexion classe"],
        ["😕","confused face","confus"],["😟","worried face","inquiet"],
        ["🙁","slightly frowning","triste"],["☹️","frowning face","triste"],
        ["😮","open mouth","surprise"],["😯","hushed face","surprise"],
        ["😲","astonished face","choque surprise"],["😳","flushed face","gene rougir"],
        ["🥺","pleading face","supplication triste"],["😦","frowning open mouth","choque"],
        ["😧","anguished face","choque peur"],["😨","fearful face","peur"],
        ["😰","anxious sweat","stress peur"],["😥","sad relieved","triste soulage"],
        ["😢","crying face","triste pleure"],["😭","loudly crying","pleure triste"],
        ["😱","face screaming fear","peur cri"],["😖","confounded face","confus enerve"],
        ["😣","persevering face","effort difficile"],["😞","disappointed face","decu"],
        ["😓","downcast sweat","stress"],["😩","weary face","fatigue enerve"],
        ["😫","tired face","fatigue"],["🥱","yawning face","fatigue baille"],
        ["😤","triumph face","fier colere"],["😡","pouting face","colere enerve"],
        ["😠","angry face","colere"],["🤬","face with symbols mouth","colere insulte"],
        ["😈","smiling imp","diable"],["👿","angry imp","diable colere"],
        ["💀","skull","mort"],["☠️","skull crossbones","mort danger"],
        ["💩","poop","caca"],["🤡","clown face","clown"],
        ["👹","ogre","monstre"],["👺","goblin","monstre"],
        ["👻","ghost","fantome halloween"],["👽","alien","extraterrestre"],
        ["🤖","robot","robot"],["😺","grinning cat","chat content"],
        ["😹","cat tears joy","chat rire"],["😻","heart eyes cat","chat amour"],
        ["👋","waving hand","salut bonjour au revoir"],["🤚","raised back hand","main"],
        ["🖐️","hand fingers splayed","main stop"],["✋","raised hand","stop main"],
        ["🖖","vulcan salute","main"],["👌","ok hand","ok parfait"],
        ["🤌","pinched fingers","geste italien"],["🤏","pinching hand","petit peu"],
        ["✌️","victory hand","victoire paix"],["🤞","crossed fingers","chance croise"],
        ["🤟","love you gesture","amour geste"],["🤘","sign of the horns","rock"],
        ["🤙","call me hand","appelle moi"],["👈","backhand left","gauche"],
        ["👉","backhand right","droite"],["👆","backhand up","haut"],
        ["🖕","middle finger","doigt honneur"],["👇","backhand down","bas"],
        ["☝️","index up","index attention"],["👍","thumbs up","pouce content valide oui"],
        ["👎","thumbs down","pouce non refuse"],["✊","raised fist","poing"],
        ["👊","oncoming fist","poing coup"],["🤛","left facing fist","poing"],
        ["🤜","right facing fist","poing"],["👏","clapping hands","applaudir bravo"],
        ["🙌","raising hands","celebration youpi"],["👐","open hands","ouvert"],
        ["🤲","palms together up","priere offrande"],["🤝","handshake","poignee main accord"],
        ["🙏","folded hands","priere merci svp"],["✍️","writing hand","ecrire"],
        ["💅","nail polish","ongles"],["🤳","selfie","selfie"],
        ["💪","flexed biceps","muscle fort"],["🦾","mechanical arm","bras robot"],
        ["🦵","leg","jambe"],["🦶","foot","pied"],
        ["👂","ear","oreille"],["👃","nose","nez"],
        ["🧠","brain","cerveau intelligence"],["👀","eyes","yeux regarder"],
        ["👁️","eye","oeil"],["👅","tongue","langue"],
        ["👄","mouth","bouche"],["💋","kiss mark","bisou rouge levres"],
        ["🩸","drop of blood","sang"],["❤️","red heart","amour coeur"],
        ["🧡","orange heart","coeur orange"],["💛","yellow heart","coeur jaune amitie"],
        ["💚","green heart","coeur vert"],["💙","blue heart","coeur bleu"],
        ["💜","purple heart","coeur violet"],["🖤","black heart","coeur noir"],
        ["🤍","white heart","coeur blanc"],["🤎","brown heart","coeur marron"],
        ["💔","broken heart","coeur brise triste"],["❣️","heart exclamation","coeur"],
        ["💕","two hearts","amour coeurs"],["💞","revolving hearts","amour coeurs"],
        ["💓","beating heart","coeur battement"],["💗","growing heart","coeur"],
        ["💖","sparkling heart","coeur etincelle"],["💘","heart arrow","amour cupidon"],
        ["💝","heart with ribbon","cadeau coeur"],["💟","heart decoration","coeur"],
        ["☮️","peace symbol","paix"],["✝️","latin cross","croix religion"],
        ["🔥","fire","feu hot cool"],["✨","sparkles","brillant etincelle"],
        ["🌟","glowing star","etoile brillant"],["⭐","star","etoile"],
        ["💫","dizzy star","etoile"],["⚡","high voltage","eclair energie"],
        ["💥","collision","explosion boom"],["💯","hundred points","100 parfait"],
        ["💢","anger symbol","colere"],["💨","dashing away","vite fuite"],
        ["💦","sweat droplets","transpiration"],["💤","zzz","dodo sommeil"],
        ["🎉","party popper","fete celebration"],["🎊","confetti ball","fete celebration"],
        ["🎈","balloon","ballon fete"],["🎁","wrapped gift","cadeau"],
        ["🏆","trophy","trophee victoire"],["🥇","gold medal","medaille or premier"],
        ["🥈","silver medal","medaille argent"],["🥉","bronze medal","medaille bronze"],
        ["🎯","direct hit","cible objectif"],["🎮","video game","jeu manette"],
        ["🎲","game die","de jeu hasard"],["🎵","musical note","musique"],
        ["🎶","musical notes","musique"],["🎤","microphone","chant micro"],
        ["🎧","headphone","musique ecouteurs"],["📷","camera","photo appareil"],
        ["📸","camera flash","photo"],["🎬","clapper board","cinema film"],
        ["💡","light bulb","idee ampoule"],["🔦","flashlight","lampe torche"],
        ["🕯️","candle","bougie"],["📌","pushpin","epingle"],
        ["📍","round pushpin","localisation carte"],["🔒","locked","verrouille securite"],
        ["🔓","unlocked","deverrouille"],["🔑","key","cle"],
        ["🗝️","old key","cle"],["🔨","hammer","marteau outil"],
        ["🛠️","hammer wrench","outils reparation"],["⚙️","gear","engrenage parametre"],
        ["🔗","link","lien chaine"],["📎","paperclip","trombone"],
        ["📏","straight ruler","regle mesure"],["📐","triangular ruler","regle geometrie"],
        ["✂️","scissors","ciseaux couper"],["🖊️","pen","stylo"],
        ["✏️","pencil","crayon ecrire"],["📝","memo","note ecrire"],
        ["📄","page facing up","document page"],["📃","page with curl","document"],
        ["📑","bookmark tabs","onglets document"],["📊","bar chart","graphique statistiques"],
        ["📈","chart increasing","graphique croissance"],["📉","chart decreasing","graphique baisse"],
        ["📅","calendar","calendrier date"],["📆","tear off calendar","calendrier"],
        ["🗓️","spiral calendar","calendrier"],["⏰","alarm clock","reveil heure"],
        ["⏱️","stopwatch","chronometre"],["⌛","hourglass done","sablier temps"],
        ["⏳","hourglass not done","sablier attente"],["💻","laptop","ordinateur pc"],
        ["🖥️","desktop computer","ordinateur pc"],["⌨️","keyboard","clavier"],
        ["🖱️","computer mouse","souris"],["💾","floppy disk","sauvegarde disquette"],
        ["💿","optical disk","cd disque"],["📀","dvd","dvd disque"],
        ["🔌","electric plug","prise electrique"],["🔋","battery","batterie"],
        ["📱","mobile phone","telephone portable"],["☎️","telephone","telephone"],
        ["📞","telephone receiver","appel telephone"],["📡","satellite antenna","antenne signal"],
        ["📶","signal bars","signal reseau wifi"],["📧","email","email mail"],
        ["✉️","envelope","email lettre"],["📩","envelope arrow","email recu"],
        ["📤","outbox tray","envoi"],["📥","inbox tray","reception"],
        ["📦","package","colis boite"],["🗑️","wastebasket","poubelle supprimer"],
        ["🌍","globe europe africa","monde terre"],["🌎","globe americas","monde terre"],
        ["🌏","globe asia australia","monde terre"],["🌐","globe meridians","internet monde"],
        ["☀️","sun","soleil"],["🌤️","sun small cloud","soleil nuage"],
        ["⛅","sun cloud","nuage soleil"],["🌥️","sun large cloud","nuage"],
        ["☁️","cloud","nuage"],["🌦️","sun rain cloud","pluie soleil"],
        ["🌧️","cloud rain","pluie"],["⛈️","cloud lightning rain","orage"],
        ["🌩️","cloud lightning","orage eclair"],["❄️","snowflake","neige froid"],
        ["☃️","snowman","bonhomme neige"],["🌈","rainbow","arc en ciel"],
        ["🌙","crescent moon","lune nuit"],["🌕","full moon","lune pleine"],
        ["🚀","rocket","fusee espace lancement"],["🛸","flying saucer","ovni"],
        ["⭐","star basic","etoile"],["🪐","ringed planet","planete espace"],
        ["🚗","automobile","voiture"],["🚕","taxi","taxi"],
        ["🚌","bus","bus"],["🚓","police car","police voiture"],
        ["🚑","ambulance","ambulance urgence"],["🚒","fire engine","pompier camion"],
        ["🚲","bicycle","velo"],["🛴","kick scooter","trottinette"],
        ["🏍️","motorcycle","moto"],["✈️","airplane","avion voyage"],
        ["🚂","locomotive","train"],["🚆","train","train"],
        ["⛵","sailboat","bateau voile"],["🚢","ship","bateau"],
        ["🏠","house","maison"],["🏡","house garden","maison jardin"],
        ["🏢","office building","bureau immeuble"],["🏫","school","ecole"],
        ["🏥","hospital","hopital"],["🏦","bank","banque"],
        ["🏨","hotel","hotel"],["⛪","church","eglise"],
        ["🗺️","world map","carte monde voyage"],["🧳","luggage","valise voyage"],
        ["🍕","pizza","pizza nourriture"],["🍔","hamburger","burger nourriture"],
        ["🍟","french fries","frites"],["🌭","hot dog","hot dog"],
        ["🥪","sandwich","sandwich"],["🌮","taco","taco"],
        ["🌯","burrito","burrito"],["🍗","poultry leg","poulet viande"],
        ["🍖","meat on bone","viande"],["🍳","cooking","oeuf cuisine"],
        ["🍝","spaghetti","pates"],["🍜","steaming bowl","ramen soupe"],
        ["🍣","sushi","sushi"],["🍱","bento box","bento repas"],
        ["🍩","doughnut","donut dessert"],["🍪","cookie","cookie biscuit"],
        ["🎂","birthday cake","gateau anniversaire"],["🍰","shortcake","gateau dessert"],
        ["🧁","cupcake","cupcake dessert"],["🍫","chocolate bar","chocolat"],
        ["🍬","candy","bonbon"],["🍭","lollipop","sucette bonbon"],
        ["🍎","red apple","pomme fruit"],["🍌","banana","banane fruit"],
        ["🍇","grapes","raisin fruit"],["🍓","strawberry","fraise fruit"],
        ["🍉","watermelon","pasteque fruit"],["🍑","peach","peche fruit"],
        ["🥑","avocado","avocat"],["🍅","tomato","tomate"],
        ["☕","hot beverage","cafe boisson"],["🍵","tea","the boisson"],
        ["🍺","beer mug","biere boisson"],["🍻","clinking beer mugs","biere sante"],
        ["🍷","wine glass","vin boisson"],["🍸","cocktail glass","cocktail"],
        ["🍹","tropical drink","cocktail boisson"],["🥂","clinking glasses","sante fete"],
        ["🥤","cup with straw","boisson soda"],["💧","droplet","goutte eau"],
        ["🎓","graduation cap","diplome etudes"],["📚","books","livres etudes"],
        ["📖","open book","livre lecture"],["🔖","bookmark","marque page"],
        ["✅","check mark button","valide ok coche"],["❌","cross mark","erreur croix non"],
        ["❓","question mark","question"],["❗","exclamation mark","attention important"],
        ["⚠️","warning sign","attention danger"],["🚫","prohibited","interdit non"],
        ["♻️","recycling symbol","recyclage"],["🔁","repeat","repeter boucle"],
        ["🔀","shuffle tracks","aleatoire melange"],["▶️","play button","jouer lecture"],
        ["⏸️","pause button","pause"],["⏹️","stop button","stop"],
        ["⏭️","next track","suivant"],["⏮️","previous track","precedent"],
        ["🔊","speaker high volume","son volume"],["🔇","muted speaker","muet"],
        ["🔔","bell","cloche notification"],["🔕","bell with slash","silence notification"],
        ["🇫🇷","flag france","france drapeau"],["🇺🇸","flag united states","usa drapeau"],
        ["🇬🇧","flag united kingdom","angleterre drapeau"],["🇩🇪","flag germany","allemagne drapeau"],
        ["🇪🇸","flag spain","espagne drapeau"],["🇮🇹","flag italy","italie drapeau"],
        ["🇯🇵","flag japan","japon drapeau"],["🇨🇦","flag canada","canada drapeau"],
        ["🇧🇪","flag belgium","belgique drapeau"],["🇨🇭","flag switzerland","suisse drapeau"]
    ]
}
